name: Publish prerelease

# Since the action `salsify/action-detect-and-tag-new-version` does not work
# in a pull request (see
# https://github.com/salsify/action-detect-and-tag-new-version/issues/6) this
# action publishes a docker container whenever one pushes to a branch name which
# starts with `prerelease`. Thus this is an easy way to publish prerelease.
#
# TODO: Remove duplicate code from copy and pasting `docker.yml`
on:
  push:
    branches:
      - prerelease**

jobs:
  push-prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_KEY_CONTAINER_REGISTRY }}'
      - uses: google-github-actions/setup-gcloud@v2
      - run: gcloud auth configure-docker
      - uses: docker/build-push-action@v5
        with:
          push: true
          file: ./Dockerfile
          tags: eu.gcr.io/serlo-shared/serlo-mysql-database:${{ github.ref_name }}
      - name: Test for mysql in the serlo-mysql-database image
        run:
          docker run --entrypoint='' --rm eu.gcr.io/serlo-shared/serlo-mysql-database:${{ github.ref_name }} mysql --version
