name: Publish prerelease

# Since the action `salsify/action-detect-and-tag-new-version` does not work
# in a pull request (see
# https://github.com/salsify/action-detect-and-tag-new-version/issues/6) this
# action publishes a docker container whenever one pushes to a branch name which
# starts with `prerelease`. Thus this is an easy way to publish prerelease.
#
# TODO: Remove duplicate code from copy and pasting `docker.yml`
on:
  push:
    branches:
      - prerelease**

jobs:
  push-prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          file: ./Dockerfile
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
      - name: Test for mysql in the serlo-mysql-database image
        run:
          docker run --entrypoint='' --rm ghcr.io/${{ github.repository }}:${{ github.ref_name }} mysql --version
